### ISSUE TITLE
plumOS_RG350_beta_P2 Download Keeps Failing.

### ISSUE THREAD

**Issue by Wozza2014** [game-de-it/plumOS-jz47xx#2]
plumOS_RG350_beta_P2 download keeps failing.

Please fix.

Thanks.

**Comment by game-de-it** [comment]
I just tried downloading it on my MacBook and Windows PC, and it downloaded without any problems.
Try clearing your browser cache or trying the download again after a few days.

**Comment by Wozza2014** [comment]
Hi,

Thanks for the quick reply.  

I will try downloading it on my laptop.  Currently trying it on a pi 4 and it has failed multiple times with both Firefox and Chromium.

Regards,
Warren.

**Comment by Wozza2014** [comment]
Hi,

I tried my laptop and it failed again. All downloads seem to fail at around 500MB-600MB.  

Could you upload it to another hosting site and post a link here?

**Comment by game-de-it** [comment]
I uploaded it to another repository.
If you can't download it from here either, please contact github support yourself.

https://github.com/game-de-it/testrepo/releases/tag/test15

**Comment by Wozza2014** [comment]
Hi,

Thanks for the link but it failed again.  Maybe it is a github problem.  I will try again in a few days.  

P.S. Sorry to bother you on a Sunday!

Regards,
Warren.

**Comment by game-de-it** [comment]
No problem.

Please try downloading again another day.

Good luck!

**Comment by Wozza2014** [comment]
Hi.

It worked at the library.  It failed within seconds of downloading then I managed to reconnect it and it downloaded it all.  So definitely something a bit off regarding the github servers.

Regards,
Warren.
